### ISSUE TITLE
Snap ML version comparison broken for `snapml==1.10.0`

### ISSUE THREAD

**Issue by tdoublep** [IBM/lale#1238]
We are releasing a new version of Snap ML (v1.10.0) and the Lale tests in our CI are failing due to this comparison being evaluated as False:

https://github.com/IBM/lale/blob/d441affb6e777de30f98636584e43484d5a82661/lale/lib/snapml/snap_boosting_machine_classifier.py#L83

Probably this shouldn't be a string greater-than comparison, there should be a more robust way to do it.

**Comment by shinnar** [comment]
yes, we should use a proper version comparison. I will work on fixing this.

**Comment by tdoublep** [comment]
@shinnar Thanks! It is not blocking us for now, so not urgent.

**Comment by shinnar** [comment]
This should be fixed in the latest testpypi release of lale (https://test.pypi.org/project/lale/0.7.2.post2210261806/)
@tdoublep could you confirm that it is fixed with that version?
