### ISSUE TITLE
DOC: environment requirements

### ISSUE THREAD

**Issue by rootsmusic** [IBM/lale#1366]
I'm trying to understand the difference between core and full flavors, but I don't see any requirements.txt or pyproject.toml.  What are their dependencies and which versions?

**Comment by hirzel** [comment]
The dependencies and their versions are documented in [setup.py](https://github.com/IBM/lale/blob/master/setup.py).

**Comment by rootsmusic** [comment]
No @hirzel, _some_ versions are documented in setup.py.  For example, I want to watch this repo's releases for when one will support [numpy 2.0.0](https://github.com/numpy/numpy/releases/tag/v2.0.0rc1).

**Comment by shinnar** [comment]
I think there may be some confusion.
The setup.py file @hirzel linked to is indeed where we have our required dependencies. 
As can be seen in that file, there is no upper bound on `numpy`, and in fact, as of version `0.8.0` of lale, we do indeed support numpy `2.0.0`.

The difference between "full" and "core", i.e. `lale` and `lale[full]` is that "core" depends on all the functionality needed for core lale functionality, which includes wrappers for many scikit-learn operators.

Lale also includes operator wrappers for operators in a number of third party libraries, such as aif360 and snapml.  These will only work if the underlying library is installed.  `lale[full]` installs all of these libraries as well, so lale operator wrappers should "just work".  This is helpful for getting started, although more advanced users may want more control over their set of dependencies.

**Comment by rootsmusic** [comment]
Ok @shinnar, pandas's next version (2.2.2) will support numpy 2.0.0.  Please document what are the intended uses for lale[fairness] and lale[tutorial].  Thanks.

**Comment by shinnar** [comment]
they give you additional dependencies for users interested in wrappers for
- lale[fairness]: operators for fairness
- lale[tutorial]: operators used in the kdd tutorial notebooks.
