### ISSUE TITLE
DOC: demo videos

### ISSUE THREAD

**Issue by rootsmusic** [IBM/lale#1367]
Are videos available for your [demo notebooks](https://github.com/IBM/lale/tree/master/examples) to introduce this package's features?  I see [an outline](https://github.com/IBM/lale/tree/master/examples/kdd22#tutorial-outline) that described the kdd22 notebooks.  But I don't see one for the ones that aren't from KDD.  Thanks.

**Comment by hirzel** [comment]
There are various videos, some of which correspond to demo notebooks:
- Nov 2019 [Type-driven Automated Learning with Lale](https://www.youtube.com/watch?v=R51ZDJ64X18)
- Jan 2020 [IBM Lale - Open Source Directions hosted by Quansight](https://www.youtube.com/watch?v=szXkof_IiGc)
- Aug 2020 [Lale: Type-driven Auto-ML with Scikit-learn](https://www.youtube.com/watch?v=NfOkUEUH_y0)
- Sep 2020 [Lale: Consistent Automated Machine Learning](https://www.youtube.com/watch?v=0vUx2lqvJGs)
- Aug 2021 [Lale.jl: Library for Automated Machine Learning](https://www.youtube.com/watch?v=4ayA_EWWlqk)
- Nov 2021 [Gradual AutoAI](https://www.youtube.com/watch?v=yweWSZha4aA)
- Nov 2022 [Fairness for Scikit-Learn Pipelines with Lale](https://www.youtube.com/watch?v=0eKkM9jL28A)

**Comment by rootsmusic** [comment]
Thanks @hirzel!  The first video is linked in [README.md](https://github.com/IBM/lale/blob/master/README.md), but I was interested in the KDD notebooks.
