### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by Albert65** [IBM/lale#218]
Dear All,
After installation of Lale followed by package update I got some pip errors:
```
ERROR: lale 0.3.3 has requirement hyperopt==0.1.2, but you'll have hyperopt 0.2.3 which is incompatible.
ERROR: lale 0.3.3 has requirement jsonschema==2.6.0, but you'll have jsonschema 3.2.0 which is incompatible.
ERROR: lale 0.3.3 has requirement pandas<=0.25.3, but you'll have pandas 1.0.1 which is incompatible.
ERROR: lale 0.3.3 has requirement scikit-learn==0.20.3, but you'll have scikit-learn 0.22.2.post1 which is incompatible.
```
Should I downgrade conflicting packages?

**Comment by hirzel** [comment]
Hi @Albert65 , based on your comment, we have updated Lale to use the latest hyperopt and jsonschema. However, due to various factors, we cannot update the other dependencies at this point. If this causes any difficulties, we recommend using a Python virtual environment to use those versions.
