### ISSUE TITLE
Segmentation fault: 11 - SMAC - MacOS catalina

### ISSUE THREAD

**Issue by tsiakmaki** [IBM/lale#352]
Hi all and thank you for your contribution. 

I am trying to use SMAC optimizer in my tests on a Mac with Catalina os. 
I have 
- installed swig
- run the: CFLAGS=-stdlib=libc++  pip install smac
- run the: pip install lale[full]
in my virtual python environment, but running my code with SMAC optimizer with my custom operator, and I am getting: 
**Segmentation fault: 11**
Any ideas what i have done wrong? 

(when using Hyperopt, I am getting results)

Thank you in advance for you time.

**Comment by hirzel** [comment]
Thank you for your feedback! Quoting from the Auto-Sklearn [installation instructions](https://automl.github.io/auto-sklearn/master/installation.html#mac-osx):

> We currently do not know if auto-sklearn works on OSX.

Also, some SMAC users have reported difficulties with segmentation faults in this [issue](https://github.com/automl/auto-sklearn/issues/688). That means this might be a problem in the underlying library and it is unclear whether there is anything we can do at the Lale level that would alleviate it.

**Comment by tsiakmaki** [comment]
I was unable to fix it. Anyway, thank you for your time.
