### ISSUE TITLE
Hyperopt Algorithm used 

### ISSUE THREAD

**Issue by tsiakmaki** [IBM/lale#390]
Not actually an issue, just a question. 

Hyperopt supports 
Random Search, 
Tree of Parzen Estimators (TPE),  and
Adaptive TPE.

When using optimizer Hyperopt in lale, which is the search algorithm behind? 

Thank you in advance for your time and contribution.

**Comment by hirzel** [comment]
Good question. Right now we just use TPE:

https://github.com/IBM/lale/blob/36178300e1f60694e9a846bb1f326c0dc422be4d/lale/lib/lale/hyperopt.py#L151

If desired, it should be fairly easy to expose the choice of algorithm as an argument to the init method of the lale.lib.lale.Hyperopt operator.

**Comment by tsiakmaki** [comment]
Thank you for your reply. 
I kind of hoping for this set up :)

**Comment by hirzel** [comment]
Hyperopt now has an *algo* argument: https://lale.readthedocs.io/en/latest/modules/lale.lib.lale.hyperopt.html

**Comment by tsiakmaki** [comment]
nice to know. thank you.
