### ISSUE TITLE
Status of support for pandas>=1.1

### ISSUE THREAD

**Issue by clgarciga** [IBM/lale#470]
Wondering if this is forthcoming in the near future? Thank you!

**Comment by kiran-kate** [comment]
Is not under active consideration, but I am adding an issue in our internal issue tracker to consider this. Is this a blocker for you?

**Comment by clgarciga** [comment]
'Blocker' is not the right word, but it is problematic when a project uses pandas >= 1.1 and then I get to the modeling phase and have to create a new env and/or a new project just to be able to use lale.

**Comment by clgarciga** [comment]
I also did want to say, I appreciate your consideration and your adding it to your internal issue tracker! Thank you!

**Comment by hirzel** [comment]
Lale should work with the latest pandas now.

**Comment by clgarciga** [comment]
Thank you!
