### ISSUE TITLE
Make parameter names in schemas.py consistent with json schema parameters names.

### ISSUE THREAD

**Issue by kiran-kate** [IBM/lale#648]
lale/schemas.py has classes that capture data types and options to be used as arguments to customize_schema. Some of the parameters passed to these classes use short forms of their json schema counterparts. For example, in the json schemas, we have `minimumForOptimizer` and in schemas.py, we have `minForOptimizer`. Renaming these parameters from schemas.py to match those from the json schema will make it easier to use. Here is the desired mapping:

1. `minimumForOptimizer` instead of `minForOptimizer`
2. `maximumForOptimizer` instead of `maxForOptimizer`
3. `minimum` instead of `min`
4. `maximum` instead of `max`
5. `exclusiveMinimum` instead of `exclusiveMin`
6. `exclusiveMaximum` instead of `exclusiveMax`

**Comment by OBITORASU** [comment]
I can work on this one :)

**Comment by shinnar** [comment]
closed by #649
