### ISSUE TITLE
StackingClassifier and StackingRegressor

### ISSUE THREAD

**Issue by hirzel** [IBM/lale#655]
Scikit-learn 0.22 introduced [StackingClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.StackingClassifier.html) and [StackingRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.StackingRegressor.html#sklearn.ensemble.StackingRegressor).  These operators train the final estimator using "cross-validated predictions of the base estimators", which should reduce over-fitting and make the ensemble more effective.  We should wrap StackingClassifier and StackingRegressor as higher-order operators in Lale.

**Comment by mfeffer** [comment]
Addressed with https://github.com/IBM/lale/pull/713
