### ISSUE TITLE
Documentation hyperlinks from output of visualize to open in a new tab.

### ISSUE THREAD

**Issue by kiran-kate** [IBM/lale#662]
The output of  `visualize` method on Lale operators adds a hyperlink to each of the operator nodes. The hyperlink points to the documentation of the operator. Currently, clicking on the link opens the documentation on the current page. Changing this to open in a new tab might be easier for the users.

**Comment by hirzel** [comment]
Done: https://nbviewer.jupyter.org/github/IBM/lale/blob/master/examples/docs_guide_for_sklearn_users.ipynb#1.2-Inspecting-the-Results-of-Automation
