### ISSUE TITLE
Improve interpretability of constraint list for operators in documentation

### ISSUE THREAD

**Issue by jsntsay** [IBM/lale#725]
"dict of ___" portion of constraint list for operators in the documentation ([such as with LinearSVC](https://lale.readthedocs.io/en/latest/modules/lale.lib.sklearn.linear_svc.html?highlight=linearsvc)) was difficult for study participants to understand, should have some prose or assistance to help understand what it means.

**Comment by hirzel** [comment]
Fixed by PR https://github.com/IBM/lale/pull/739
