### ISSUE TITLE
Customize_schema or get_param_ranges do not parse `AnyOf(types=[Bool(), Null()], default=Null())` correctly.

### ISSUE THREAD

**Issue by kiran-kate** [IBM/lale#837]
The `shrinking` hyperparameter of `lale.lib.sklearn.SVR` can be customized as follows:

```Python
SVR = SVR.customize_schema(
    shrinking=AnyOf(
        types=[Bool(), Null()],
        default=Null(),
        desc="Whether to use the shrinking heuristic."))

```

The expected output of `get_param_ranges()` on the customized operator should have `'shrinking': (False, True, None)`, but this just results in `'shrinking':(None)` as of now.

**Comment by shinnar** [comment]
Note that the example should actually be:
```
SVR = SVR.customize_schema(
            shrinking=AnyOf(
                types=[Bool(), Null()],
                default=None,
                desc="Whether to use the shrinking heuristic."))
```
since defaults take a value, not a schema
